import https from 'https';
import { YoutubeTranscript } from 'youtube-transcript';

interface TranscriptLine {
  text: string;
  start: number;
  dur: number;
}

export interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface AdChapter {
  title: string;
  startMs: number;
  endMs: number;
}

export interface VideoMetadata {
  title: string;
  author: string;
  subscriberCount: string;
  viewCount: string;
  publishDate: string;
}

interface PageData {
  availableLanguages: CaptionTrack[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
}

const REQUEST_TIMEOUT = 30000; // 30 seconds
const WEB_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

/**
 * Makes an HTTPS request and returns the response body
 */
function httpsRequest(options: https.RequestOptions, data?: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const req = https.request({ ...options, timeout: REQUEST_TIMEOUT }, (res) => {
      if (res.statusCode && (res.statusCode < 200 || res.statusCode >= 300)) {
        reject(new Error(`HTTP ${res.statusCode}: ${res.statusMessage || 'Unknown error'}`));
        return;
      }
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => resolve(body));
    });
    req.on('error', (err) => reject(new Error(`Network error: ${err.message}`)));
    req.on('timeout', () => { req.destroy(); reject(new Error(`Request timeout after ${REQUEST_TIMEOUT}ms`)); });
    if (data) req.write(data);
    req.end();
  });
}

/**
 * Fetches the YouTube video page and extracts metadata, languages, and ad chapters
 */
async function getPageData(videoId: string): Promise<PageData> {
  let html: string;
  try {
    html = await httpsRequest({
      hostname: 'www.youtube.com',
      path: `/watch?v=${videoId}`,
      method: 'GET',
      headers: {
        'User-Agent': WEB_USER_AGENT,
        'Accept-Language': 'en-US,en;q=0.9'
      }
    });
  } catch (err) {
    throw new Error(`Failed to fetch video page: ${(err as Error).message}`);
  }

  // Extract available caption tracks
  const availableLanguages: CaptionTrack[] = [];
  const captionsMatch = html.match(/"captions":\{"playerCaptionsTracklistRenderer":\{"captionTracks":(\[[^\]]+\])/);
  if (captionsMatch) {
    try {
      const tracks = JSON.parse(captionsMatch[1]);
      for (const track of tracks) {
        if (track.languageCode) {
          availableLanguages.push({
            languageCode: track.languageCode,
            name: track.name?.simpleText || track.name?.runs?.[0]?.text || track.languageCode,
            isAutoGenerated: track.kind === 'asr'
          });
        }
      }
    } catch (e) {
      console.error(`[youtube-fetcher] Warning: Could not parse caption tracks for video ${videoId}`);
    }
  }

  // Extract chapters and identify ad chapters
  const adChapters: AdChapter[] = [];
  const adMarkers = [
    '(werbung)', '(ad)', '(ads)', '(sponsor)', '(sponsored)',
    '(promo)', '(promotion)', '(anzeige)', '(reklame)',
    '[werbung]', '[ad]', '[ads]', '[sponsor]', '[sponsored]',
    '[promo]', '[promotion]', '[anzeige]', '[reklame]'
  ];

  const chapterMatches = [...html.matchAll(/"chapterRenderer":\s*\{[^}]*"title":\s*\{\s*"simpleText":\s*"([^"]+)"[^}]*\}[^}]*"timeRangeStartMillis":\s*"?(\d+)"?/g)];

  interface Chapter { title: string; startMs: number; isAd: boolean; }
  const chapters: Chapter[] = chapterMatches.map(match => ({
    title: match[1],
    startMs: parseInt(match[2], 10),
    isAd: adMarkers.some(marker => match[1].toLowerCase().includes(marker))
  }));

  for (let i = 0; i < chapters.length; i++) {
    if (chapters[i].isAd) {
      const nextChapter = chapters[i + 1];
      const endMs = nextChapter ? nextChapter.startMs : chapters[i].startMs + 300000;
      adChapters.push({ title: chapters[i].title, startMs: chapters[i].startMs, endMs });
    }
  }

  // Extract video metadata
  const titleMatch = html.match(/"videoDetails":\{.*?"title":"([^"]+)"/);
  const authorMatch = html.match(/"videoDetails":\{.*?"author":"([^"]+)"/);
  const subsMatch = html.match(/"subscriberCountText":\{"accessibility":\{"accessibilityData":\{"label":"([^"]+)"/);
  const viewsMatch = html.match(/"viewCount":"(\d+)"/);
  const dateMatch = html.match(/"publishDate":"([^"]+)"/);

  let subs = (subsMatch?.[1] || '').replace(/ subscribers?/i, '').replace(/ thousand/i, 'k').replace(/ million/i, 'M').replace(/ billion/i, 'B');
  const views = viewsMatch?.[1] || '';
  const viewNum = parseInt(views, 10);
  const viewsFormatted = Number.isNaN(viewNum) ? '' : viewNum >= 1_000_000 ? (viewNum / 1_000_000).toFixed(1) + 'M' : viewNum >= 1_000 ? (viewNum / 1_000).toFixed(1) + 'k' : views;
  const dateRaw = dateMatch?.[1] || '';
  const dateShort = dateRaw.split('T')[0];

  const metadata: VideoMetadata = {
    title: titleMatch?.[1] || '',
    author: authorMatch?.[1] || '',
    subscriberCount: subs,
    viewCount: viewsFormatted,
    publishDate: dateShort
  };

  return { availableLanguages, adChapters, metadata };
}

export interface SubtitleResult {
  lines: TranscriptLine[];
  requestedLang: string;
  actualLang: string;
  availableLanguages: CaptionTrack[];
  adChapters: AdChapter[];
  metadata: VideoMetadata;
}

/**
 * Returns available caption languages for a video without fetching the full transcript
 */
export async function getAvailableLanguages(videoID: string): Promise<CaptionTrack[]> {
  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }
  const { availableLanguages } = await getPageData(videoID);
  return availableLanguages;
}

/**
 * Fetches transcript using the youtube-transcript package (uses timedtext API).
 * Falls back to available languages if the requested language is not available.
 */
export async function getSubtitles(options: {
  videoID: string;
  lang?: string;
  enableFallback?: boolean;
}): Promise<SubtitleResult> {
  const { videoID, lang = 'en', enableFallback = true } = options;

  if (!videoID || typeof videoID !== 'string') {
    throw new Error('Invalid video ID: must be a non-empty string');
  }

  // Get page data for metadata, languages, and ad chapters
  const { availableLanguages, adChapters, metadata } = await getPageData(videoID);

  // Determine which language to use
  let targetLang = lang;
  if (availableLanguages.length > 0) {
    const hasRequestedLang = availableLanguages.some(t => t.languageCode === lang);
    if (!hasRequestedLang && enableFallback) {
      const hasEnglish = availableLanguages.some(t => t.languageCode === 'en');
      targetLang = hasEnglish ? 'en' : (availableLanguages[0]?.languageCode || lang);
      console.error(`[youtube-fetcher] Language '${lang}' not available, falling back to '${targetLang}'`);
    } else if (!hasRequestedLang) {
      throw new Error(`Language '${lang}' not available. Available: ${availableLanguages.map(t => t.languageCode).join(', ')}`);
    }
  }

  // Fetch transcript using youtube-transcript package
  let rawLines: { text: string; offset: number; duration: number }[];
  try {
    rawLines = await YoutubeTranscript.fetchTranscript(videoID, { lang: targetLang });
  } catch (err) {
    throw new Error(`Failed to fetch transcript: ${(err as Error).message}. The video may not have captions in '${targetLang}'.`);
  }

  // Convert to TranscriptLine format
  const lines: TranscriptLine[] = rawLines
    .map(l => ({
      text: l.text,
      start: l.offset / 1000,
      dur: l.duration / 1000
    }))
    .filter(l => l.text.trim().length > 0);

  if (lines.length === 0) {
    throw new Error('No transcript available for this video. The video may not have captions enabled.');
  }

  return {
    lines,
    requestedLang: lang,
    actualLang: targetLang,
    availableLanguages,
    adChapters,
    metadata
  };
}
